//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClanManager.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClanManager.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Clans.
        /// </summary>
        public static string Active_Clans {
            get {
                return ResourceManager.GetString("Active_Clans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Clans.
        /// </summary>
        public static string All_Clans {
            get {
                return ResourceManager.GetString("All_Clans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to home.
        /// </summary>
        public static string Back_Home {
            get {
                return ResourceManager.GetString("Back_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activate.
        /// </summary>
        public static string Button_Activate {
            get {
                return ResourceManager.GetString("Button_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ban.
        /// </summary>
        public static string Button_Ban {
            get {
                return ResourceManager.GetString("Button_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Role.
        /// </summary>
        public static string Button_Change_Role {
            get {
                return ResourceManager.GetString("Button_Change_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deactivate.
        /// </summary>
        public static string Button_Deactivate {
            get {
                return ResourceManager.GetString("Button_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete clan.
        /// </summary>
        public static string Button_DeleteClan {
            get {
                return ResourceManager.GetString("Button_DeleteClan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REMOVE.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unban.
        /// </summary>
        public static string Button_UnBan {
            get {
                return ResourceManager.GetString("Button_UnBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan Details.
        /// </summary>
        public static string Clan_Details {
            get {
                return ResourceManager.GetString("Clan_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Clan.
        /// </summary>
        public static string Create_Clan {
            get {
                return ResourceManager.GetString("Create_Clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de description for the Clan.
        /// </summary>
        public static string Enter_Clan_Description {
            get {
                return ResourceManager.GetString("Enter_Clan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Clan Name.
        /// </summary>
        public static string Enter_Clan_Name {
            get {
                return ResourceManager.GetString("Enter_Clan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter Clan Tag.
        /// </summary>
        public static string Enter_Clan_Tag {
            get {
                return ResourceManager.GetString("Enter_Clan_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Password.
        /// </summary>
        public static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your Email.
        /// </summary>
        public static string Enter_User_Email {
            get {
                return ResourceManager.GetString("Enter_User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing your request..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page not found.
        /// </summary>
        public static string Error_404 {
            get {
                return ResourceManager.GetString("Error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internal server error.
        /// </summary>
        public static string Error_500 {
            get {
                return ResourceManager.GetString("Error_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error reseting Database..
        /// </summary>
        public static string Error_Admin_ResetDB {
            get {
                return ResourceManager.GetString("Error_Admin_ResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot change Own Clan Role..
        /// </summary>
        public static string Error_CannotChangeOwnRoleException {
            get {
                return ResourceManager.GetString("Error_CannotChangeOwnRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot change the Role of a Member with same Clan Role level..
        /// </summary>
        public static string Error_CannotChangeSameRoleException {
            get {
                return ResourceManager.GetString("Error_CannotChangeSameRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while changing Member Clan Role..
        /// </summary>
        public static string Error_Clan_ChangeMemberRole_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_ChangeMemberRole_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while creating Clan..
        /// </summary>
        public static string Error_Clan_Create_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_Create_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while deleting Clan..
        /// </summary>
        public static string Error_Clan_Delete_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_Delete_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while retrieving clan details..
        /// </summary>
        public static string Error_Clan_Detail_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_Detail_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while  joining clan..
        /// </summary>
        public static string Error_Clan_Join_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_Join_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while loading clan list..
        /// </summary>
        public static string Error_Clan_List_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_List_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while removing Clan Member..
        /// </summary>
        public static string Error_Clan_RemoveMember_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_RemoveMember_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while ToggleActive Clan..
        /// </summary>
        public static string Error_Clan_ToggleActive_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_ToggleActive_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while Updating Clan Description..
        /// </summary>
        public static string Error_Clan_UpdateDescription_Controller {
            get {
                return ResourceManager.GetString("Error_Clan_UpdateDescription_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan with same Name and Tag already exists..
        /// </summary>
        public static string Error_ClanAlreadyExistsException {
            get {
                return ResourceManager.GetString("Error_ClanAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot joint Inactive Clan..
        /// </summary>
        public static string Error_ClanInactiveException {
            get {
                return ResourceManager.GetString("Error_ClanInactiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error a Clan Leader cannot be removed..
        /// </summary>
        public static string Error_ClanLeaderRemovalException {
            get {
                return ResourceManager.GetString("Error_ClanLeaderRemovalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan not found..
        /// </summary>
        public static string Error_ClanNotFoundException {
            get {
                return ResourceManager.GetString("Error_ClanNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Already clan member..
        /// </summary>
        public static string Error_MemberAlreadyInClanException {
            get {
                return ResourceManager.GetString("Error_MemberAlreadyInClanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan Member not found..
        /// </summary>
        public static string Error_MemberNotFoundException {
            get {
                return ResourceManager.GetString("Error_MemberNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No User in Session..
        /// </summary>
        public static string Error_NoSessionUserException {
            get {
                return ResourceManager.GetString("Error_NoSessionUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only Clan Leader can Delete Clan..
        /// </summary>
        public static string Error_NotClanLeaderException {
            get {
                return ResourceManager.GetString("Error_NotClanLeaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong Password. Please try again..
        /// </summary>
        public static string Error_PasswordValidationException {
            get {
                return ResourceManager.GetString("Error_PasswordValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Clan Role specified..
        /// </summary>
        public static string Error_RoleChangeException_Invalid_ClanRole {
            get {
                return ResourceManager.GetString("Error_RoleChangeException_Invalid_ClanRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Role specified..
        /// </summary>
        public static string Error_RoleChangeException_Invalid_Role {
            get {
                return ResourceManager.GetString("Error_RoleChangeException_Invalid_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot change own role..
        /// </summary>
        public static string Error_RoleChangeException_OwnRole {
            get {
                return ResourceManager.GetString("Error_RoleChangeException_OwnRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot change role of SuperAdmin..
        /// </summary>
        public static string Error_RoleChangeException_SuperAdmin {
            get {
                return ResourceManager.GetString("Error_RoleChangeException_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot set SuperAdmin role..
        /// </summary>
        public static string Error_RoleChangeException_To_SuperAdmin {
            get {
                return ResourceManager.GetString("Error_RoleChangeException_To_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session User Member Not Found..
        /// </summary>
        public static string Error_SessionUserMemberNotFoundException {
            get {
                return ResourceManager.GetString("Error_SessionUserMemberNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session user not found..
        /// </summary>
        public static string Error_SessionUserNotFoundException {
            get {
                return ResourceManager.GetString("Error_SessionUserNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your role doesn&apos;t allow you to change that user Role..
        /// </summary>
        public static string Error_ToggleBanException_AdminByAdmin {
            get {
                return ResourceManager.GetString("Error_ToggleBanException_AdminByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot ban a Clan Leader..
        /// </summary>
        public static string Error_ToggleBanException_ClanLeader {
            get {
                return ResourceManager.GetString("Error_ToggleBanException_ClanLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot (un)ban yourself..
        /// </summary>
        public static string Error_ToggleBanException_Self {
            get {
                return ResourceManager.GetString("Error_ToggleBanException_Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot ban SuperAdmin..
        /// </summary>
        public static string Error_ToggleBanException_SuperAdmin {
            get {
                return ResourceManager.GetString("Error_ToggleBanException_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while changing User Role..
        /// </summary>
        public static string Error_User_ChangeRole_Controller {
            get {
                return ResourceManager.GetString("Error_User_ChangeRole_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while creating account..
        /// </summary>
        public static string Error_User_Create_Controller {
            get {
                return ResourceManager.GetString("Error_User_Create_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while retrieving user details..
        /// </summary>
        public static string Error_User_Detail_Controller {
            get {
                return ResourceManager.GetString("Error_User_Detail_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while loading user list..
        /// </summary>
        public static string Error_User_List_Controller {
            get {
                return ResourceManager.GetString("Error_User_List_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while user login..
        /// </summary>
        public static string Error_User_Login_Controller {
            get {
                return ResourceManager.GetString("Error_User_Login_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while ToggleBan user..
        /// </summary>
        public static string Error_User_ToggleBan_Controller {
            get {
                return ResourceManager.GetString("Error_User_ToggleBan_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User already exists..
        /// </summary>
        public static string Error_UserAlreadyExistsException {
            get {
                return ResourceManager.GetString("Error_UserAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email not found..
        /// </summary>
        public static string Error_UserEmailNotFoundException {
            get {
                return ResourceManager.GetString("Error_UserEmailNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User not found..
        /// </summary>
        public static string Error_UserNotFoundException {
            get {
                return ResourceManager.GetString("Error_UserNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have a Role that allows you to do that action..
        /// </summary>
        public static string Error_WrongRoleException {
            get {
                return ResourceManager.GetString("Error_WrongRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oops! The page you are looking for does not exist..
        /// </summary>
        public static string Error404_1 {
            get {
                return ResourceManager.GetString("Error404_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The link may be broken or the page may have been moved..
        /// </summary>
        public static string Error404_2 {
            get {
                return ResourceManager.GetString("Error404_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An internal error has occurred..
        /// </summary>
        public static string Error500_1 {
            get {
                return ResourceManager.GetString("Error500_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We are working to fix it. Please try again later..
        /// </summary>
        public static string Error500_2 {
            get {
                return ResourceManager.GetString("Error500_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention !.
        /// </summary>
        public static string Index_Attention {
            get {
                return ResourceManager.GetString("Index_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RESET DATABASE.
        /// </summary>
        public static string Index_Attention_Reset {
            get {
                return ResourceManager.GetString("Index_Attention_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A button allows you to reset the database in case of data issues. Use with caution..
        /// </summary>
        public static string Index_Attention_Text {
            get {
                return ResourceManager.GetString("Index_Attention_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan side.
        /// </summary>
        public static string Index_ClanSide {
            get {
                return ResourceManager.GetString("Index_ClanSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &lt;strong&gt;clan leaders&lt;/strong&gt; have privileges to manage the members of their clan..
        /// </summary>
        public static string Index_ClanSide_Leaders {
            get {
                return ResourceManager.GetString("Index_ClanSide_Leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users can &lt;strong&gt;join or leave clans&lt;/strong&gt; according to their preferences..
        /// </summary>
        public static string Index_ClanSide_Users {
            get {
                return ResourceManager.GetString("Index_ClanSide_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can &lt;strong&gt;create, edit and delete clans&lt;/strong&gt;..
        /// </summary>
        public static string Index_ClanSide_You {
            get {
                return ResourceManager.GetString("Index_ClanSide_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to my clan management application. It allows you to organize groups, manage members, and define different access levels..
        /// </summary>
        public static string Index_Description {
            get {
                return ResourceManager.GetString("Index_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project Documentation.
        /// </summary>
        public static string Index_Doc {
            get {
                return ResourceManager.GetString("Index_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &lt;strong&gt;UserBLL&lt;/strong&gt; and &lt;strong&gt;UserController&lt;/strong&gt; classes include an example of complete documentation with error handling, roles, and business logic behavior..
        /// </summary>
        public static string Index_Doc_Txt {
            get {
                return ResourceManager.GetString("Index_Doc_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main Features.
        /// </summary>
        public static string Index_Main_Features {
            get {
                return ResourceManager.GetString("Index_Main_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can also use the name before @example.com for every user, and use that same name as password..
        /// </summary>
        public static string Index_OtherAccounts_Text {
            get {
                return ResourceManager.GetString("Index_OtherAccounts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test accounts.
        /// </summary>
        public static string Index_TestAccounts {
            get {
                return ResourceManager.GetString("Index_TestAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan management website.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User side.
        /// </summary>
        public static string Index_UserSide {
            get {
                return ResourceManager.GetString("Index_UserSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &lt;strong&gt;Admins&lt;/strong&gt; have privileges to manage users and their roles..
        /// </summary>
        public static string Index_UserSide_Admin {
            get {
                return ResourceManager.GetString("Index_UserSide_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login and use the site with different roles..
        /// </summary>
        public static string Index_UserSide_Connection {
            get {
                return ResourceManager.GetString("Index_UserSide_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leader.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My Clans.
        /// </summary>
        public static string MyClans {
            get {
                return ResourceManager.GetString("MyClans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No clans available..
        /// </summary>
        public static string No_Clan_Available {
            get {
                return ResourceManager.GetString("No_Clan_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Leader found.
        /// </summary>
        public static string No_Leader_Found {
            get {
                return ResourceManager.GetString("No_Leader_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No users available..
        /// </summary>
        public static string No_Users_Available {
            get {
                return ResourceManager.GetString("No_Users_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database reseted successfully..
        /// </summary>
        public static string Success_Admin_ResetDB {
            get {
                return ResourceManager.GetString("Success_Admin_ResetDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Member Clan Role changed successfully..
        /// </summary>
        public static string Success_Clan_ChangeMemberRole_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_ChangeMemberRole_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan successfully created..
        /// </summary>
        public static string Success_Clan_Create_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_Create_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan successfully deleted..
        /// </summary>
        public static string Success_Clan_Delete_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_Delete_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan successfully joined..
        /// </summary>
        public static string Success_Clan_Join_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_Join_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Member successfully removed from Clan..
        /// </summary>
        public static string Success_Clan_RemoveMember_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_RemoveMember_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You successfuly left the clan..
        /// </summary>
        public static string Success_Clan_RemoveSelf_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_RemoveSelf_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ToggleActive successfull..
        /// </summary>
        public static string Success_Clan_ToggleActive_Controller {
            get {
                return ResourceManager.GetString("Success_Clan_ToggleActive_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role successfully changed..
        /// </summary>
        public static string Success_User_ChangeRole_Controller {
            get {
                return ResourceManager.GetString("Success_User_ChangeRole_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account successfully created..
        /// </summary>
        public static string Success_User_Create_Controller {
            get {
                return ResourceManager.GetString("Success_User_Create_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully logged in..
        /// </summary>
        public static string Success_User_Login_Controller {
            get {
                return ResourceManager.GetString("Success_User_Login_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully logged out..
        /// </summary>
        public static string Success_User_Logout_Controller {
            get {
                return ResourceManager.GetString("Success_User_Logout_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ToggleBan successfull..
        /// </summary>
        public static string Success_User_ToggleBan_Controller {
            get {
                return ResourceManager.GetString("Success_User_ToggleBan_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Details.
        /// </summary>
        public static string User_Details {
            get {
                return ResourceManager.GetString("User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are banned..
        /// </summary>
        public static string User_IsBanned {
            get {
                return ResourceManager.GetString("User_IsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SuperAdmin.
        /// </summary>
        public static string User_SuperAdmin_Role_Info {
            get {
                return ResourceManager.GetString("User_SuperAdmin_Role_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
